cancel=Cancel
makeoffer=Offer swap
tab0recpartnerlabel=%s makes you this offer.
tab0difflabel=Difference\:
tab0header=Overview
tab0offeringlabel=offered property cards\:
tab0offermoneylabel=Offer additional money to your partner\:
tab0offerselectedlink=%d selected
tab0recofferselectedlink=%d properties
tab0partnerlabel=Your partner\:
tab0subtitle=Choose a player with whom you would like to swap properties
tab0title=Create a swap offer
tab0wishedlabel=desired property cards\:
tab0wishedmoneylabel=Request additional money from your partner\:
tab0wishedselectedlink=%d selected
tab1header=Your property cards
tab1subtitle=Which of your property cards would you like to offer? But mind\: built-up streets cannot be swapped.
tab1title=Your property cards
tab2header=Property cards of your partner
tab2subtitle=Which property cards would you like to get? But mind\: built-up streets cannot be swapped.
tab2title=Property cards of your partner
tab0rectitle=View Swap Offer
tab0recsubtitle=Here you can see an overview of the swap offer you received.
tab0recofferinglabel=Requested property cards:

tab0recwishedmoneylabel=Additionally you get the following amount of money:
tab0recoffermoneylabel=You are supposed to pay:

tab1recheader=Desired properties
tab2recheader=Offered properties
tab2recsubtitle=Your partner offers you the following properties
tab1recsubtitle=Your partner want to have the following properties from you
denyoffer=Deny
editoffer=Create a counteroffer
acceptoffer=Accept this offer
tab0recdesiredlabel=Offered property cards\:
sendCounterOffer=Send counteroffer
