title = About
generalTab = General
rulesTab = Rules
copyrightTab = Copyright
general = general_english.html
copyright = copyright_english.html
rules = rules_english.html
close = Close

tooltipClose =Click here to close the window