start = Start game
leave = Leave game
send = Send
hint_sendMessage = Enter chat message
chooseFigure = Selected figure
kickPlayer = KICK THIS PLAYER
figureViewToolTip = Change your figure with the buttons below the figure.
notEnoughPlayer=You need two players to start a game.
entered=%s entered the game
left=%s left the game
tooltipKick=Remove this player from the game.
noFigurePicked = Not all players have chosen a figure.
selectFigureButton = Select
selectFigureButtonDisabled = Unselect
readyUserTooltip = This player has chosen a figure.
NotReadyUserTooltip = This player has not yet chosen a figure.
readyLabelText =  Ready
userFigureWarning = Please select a figure.
tooltipSelect=Click here to select this figure
tooltipLeave=Click here to leave the game
tooltipStart=Click here to start the game
tooltipNextFigure=Click here to change the figure
tooltipSend=Click here to send the message
