title = Account changes
header = Here you can edit your account settings
username = Name:
language = Language:
submit = Done
cancel = Cancel
promptname = Name
errNameShort = Such a short name is not allowed.
errNameLong = Such a long name is not allowed.
errNameNotAllowed = This name is not allowed.