finish = Finish turn
onTurn=It's %s turn.
youbought=You bought %s.
anotherBought=%s bought %s.
gotMoney=%s got %d LPD.
paidMoney=%s paid %d LPD.
rolled=%s rolled %d and %d.
youGotMoney = You got %d LPD.
youPaidMoney =  You paid %d LPD.
notEnoughMoneyToPurchase=You do not have enough money to purchase %s.
notEnoughMoneyConstructHotel=You do not have enough money to construct a hotel.
notEnoughMoneyConstructHouse=You do not have enough money to construct a house.
notEnoughMoneyConstructFactory=You do not have enough money to construct a factory.
constructedHouseMsg=%s constructed a house on %s.
constructedHoteleMsg=%s constructed a hotel on %s.
constructedFactoryMsg=%s constructed a factory on %s.
lostGame=%s lost the game.
areyoudone=Are you done?
swapAccepted=%s and %s successfully made a swap.
swapDeclined=The swap offer was declined by %s.
drawedActionCard=%s drawed an action card\: "%s"
soldHouse=%s sold a house.
soldHotel=%s sold hotel.
soldFactory=%s sold a factory.
youSoldHouse=You sold a house.
youSoldHotel=You sold a hotel.
youSoldFactory=You sold a factory.
itsTurn=It's %s's turn
showStandardView=Standard view
youLost=You were not got enough to win in this city and lost the game\!
youWon=You won Las Poly and outplayed your opponents\!
congrats=congratulation\!
condolences=Too Bad\!
casinoDialogTitle=Casino
casinoDialogHeader=Roll a double and win money\!
finishturndialog_description=You can still mortgage properties, buy houses and much more. When you are ready, click the button.
lostConnection=%s lost the connection and was kicked out of the game.
lostNoMoneyLeft=%s had not enough money left and has been kicked out of the game.
leave=%s left the game.
kickedByHost=%s was kicked by the host.
youLostNoMoneyLeft=You had not enough money left and have been kicked out of the game.
itsYourTurn=It's your turn
