title=Las Poly Settings
tabGeneral=General
tabKeys=Keys
tabSound=Sound
soundLabel=Master volume
backgroundMusicLabel=Background music
soundEffectsLabel=Sound effects
save=Save
general=General
game=Game
description=Description
keyBinding=Key Binding
apply=Apply
cancel=Cancel
pressKey=Change the value by pressing a key
headerUnsaved=You have unsaved changes
contentUnsaved=Do you still want to close the settings?
yes=Yes
no=No
soundEffectsTooltip=Sound effects are special sounds that are played if special actions occur.
soundTooltip=The master volume is used for setting the general sound of the program.
backgroundMusicTooltip=The background music is the sound that is played all the time.

tooltipSave = Click here to save the settings

tooltipMute = Click here to mute this sound
tooltipUnmute = Click here to unmute the sound