title = Action card
confirm = Confirm
move=Advance to %s
gamblingTax=Pay gambling tax of %d LPD.
youGotPromoted=You've been promoted. Pay each Player %d LPD.
streetRepairs=You are assessed for street repairs. \nPay for each house %d LPD. Pay for each hotel %d LPD. Pay \
  for each factory %d LPD.
parkingFine=Parking fine %d LPD
generalRepairs=Make general repairs on all of your houses and hotels. \nPay for each house %d LPD. Pay for each hotel %d LPD.
factoryRedevelop=Redevelop all your factories. For each factory pay %d LPD.
helicopterFlight=You have booked a helicopter flight. Pay %d LPD.
magicianShow=You visited a magician show in the casino. Pay %d LPD as entrance fee.
independenceDay=It's Independence Day. You bought fireworks worth %d LPD.
lookalikeCompetition=You won in a Look-Alike contest. Collect %d LPD.
birthday=It's your birthday. All players give you %d LPD as a gift.
horseRacing=You won at a horse racing. You collect %d LPD.
pokerTable=You won at a poker table. You collect %d LPD from each player.
yardSale=You get %d LPD from a yard sale.
inherit=You inherit %d LPD.
moveForward=Advance %s space(s).
anotherCardTransaction=Pay a fine of %d LPD or take another action card.
jail=Go to jail. Move directly to jail. Do not pass "Go".
slotMachine=You won %d LPD at the Slot Machine.
roulette=You won a round of Roulette. You receive %d LPD.
boxingBet=You won a bet in boxing. You collect %d LPD.
blackJack=You won at a Black Jack table. You collect %d LPD.
baccaratGame=You won a Baccarat game. You collect %d LPD.
nextTrainStation=Move forward to the next train station.
optionCard=Take card
optionMoney=Pay money
player=Player\: